name: Build Docker Image

on:
  push:

jobs:
  build-docker-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: use checkout action
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export image
        uses: docker/build-push-action@v6
        with:
          tags: simplewebapp:latest
          outputs: type=docker, dest=${{runner.temp}}/simplewebapp.tar
      
      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with: 
          name: simplewebappartifact
          path: ${{runner.temp}}/simplewebapp.tar