name: Build Docker Image

on:
  push:

jobs:
  build-docker-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: use checkout action
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export image
        uses: docker/build-push-action@v6
        with:
          tags: simplewebapp:latest
          outputs: type=docker, dest=${{runner.temp}}/simplewebapp.tar
      
      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with: 
          name: simplewebapp
          path: ${{runner.temp}}/simplewebapp.tar

  publish-docker-image:
    name: Publish Docker image
    runs-on: ubuntu-latest
    needs: build-docker-image #add test job here later as well.
    steps:
      - name: Download app artifact from build stage.
        uses: actions/download-artifact@v4
        with:
          name: simplewebapp
          path: ${{runner.temp}}

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.LIATRIO_DOCKER_HUB_TOKEN}}

      - name: publish image to docker hub
        run: 
          docker push ${{secrets.DOCKER_HUB_USERNAME}}/simplewebapp:latest