name: Build Docker Image

on:
  push:

env:
  TEST_VERSION_TAG: mattm12525/simplewebapp:test
  LATEST_VERSION_TAG: mattm12525/simplewebapp:latest
  GITHUB_ACTION_PATH: ../app

jobs:
  build-test-publish-docker-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:    
      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.LIATRIO_DOCKER_HUB_TOKEN}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export image to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{env.TEST_VERSION_TAG}}
      
      - name: Check for correct image name 
        run: |
            echo ${PWD}
            echo $(ls ..)
            echo $(ls ../app)
            docker image ls -a

      - name: Test
        uses: liatrio/github-actions/apprentice-action@master

      - name: Build and push image to Docker
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{env.LATEST_VERSION_TAG}}