name: Build-Test-Publish Docker Image

on:
  push:
  
jobs:
  build-test-publish-docker-image:
    name: Build-Test-Publish Docker image
    runs-on: ubuntu-latest
    steps:    
      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.LIATRIO_DOCKER_HUB_TOKEN}}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export image to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: mattm12525/simplewebapp:test

      - name: Run nodeJS in background for tests
        run: docker run -p 80:80/tcp mattm12525/simplewebapp:test &            

      - name: Test
        uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91

      - name: Build and push image to Dockerhub
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mattm12525/simplewebapp:latest